CREATE TABLE campanha (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	cliente VARCHAR(255) NOT NULL,
	data_inicio DATE,
	data_termino DATE,
	status VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;